# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/widgets/repo_clickabletreeview.h \
    ./src/dialogs/repo_dialogcommit.h \
    ./src/dialogs/repo_dialogconnect.h \
    ./src/dialogs/repo_dialoghistory.h \
    ./src/primitives/repo_fontawesome.h \
    ./src/dialogs/repo_genericdialog.h \
    ./src/renderers/repo_glcwidget.h \
    ./src/widgets/repo_lineedit.h \
    ./src/widgets/repo_mdiarea.h \
    ./src/widgets/repo_mdisubwindow.h \
    ./src/renderers/repo_oculus.h \
    ./src/widgets/repo_textbrowser.h \
    ./src/dialogs/repo_transformationdialog.h \
    ./src/renderers/repo_webview.h \
    ./src/widgets/repo_widgetrepository.h \
    ./src/dialogs/repoabstractmanagerdialog.h \
    ./src/primitives/repocomboboxeditor.h \
    ./src/dialogs/repodialogabout.h \
    ./src/dialogs/repodialogoculus.h \
    ./src/dialogs/repodialogsettings.h \
    ./src/dialogs/repodialoguser.h \
    ./src/dialogs/repodialogusermanager.h \
    ./src/dialogs/repofederationdialog.h \
    ./src/widgets/repofilterabletreewidget.h \
    ./src/renderers/repooculustexturerenderer.h \
    ./src/dialogs/repoprojectmanagerdialog.h \
    ./src/dialogs/repoprojectsettingsdialog.h \
    ./src/widgets/reposelectiontreedockwidget.h \
    ./src/widgets/repowidgetassimpflags.h
SOURCES += ./src/main.cpp \
    ./src/renderers/repo_3ddiffrenderer.cpp \
    ./src/widgets/repo_clickabletreeview.cpp \
    ./src/primitives/repo_color.cpp \
    ./src/dialogs/repo_dialogcommit.cpp \
    ./src/dialogs/repo_dialogconnect.cpp \
    ./src/dialogs/repo_dialoghistory.cpp \
    ./src/primitives/repo_fontawesome.cpp \
    ./src/renderers/repo_fpscounter.cpp \
    ./src/dialogs/repo_genericdialog.cpp \
    ./src/primitives/repo_glccamera.cpp \
    ./src/renderers/repo_glcwidget.cpp \
    ./src/widgets/repo_lineedit.cpp \
    ./src/widgets/repo_mdiarea.cpp \
    ./src/widgets/repo_mdisubwindow.cpp \
    ./src/renderers/repo_oculus.cpp \
    ./src/primitives/repo_sortfilterproxymodel.cpp \
    ./src/widgets/repo_textbrowser.cpp \
    ./src/dialogs/repo_transformationdialog.cpp \
    ./src/renderers/repo_webview.cpp \
    ./src/widgets/repo_widgetrepository.cpp \
    ./src/dialogs/repoabstractmanagerdialog.cpp \
    ./src/primitives/repocomboboxdelegate.cpp \
    ./src/primitives/repocomboboxeditor.cpp \
    ./src/dialogs/repodialogabout.cpp \
    ./src/dialogs/repodialogoculus.cpp \
    ./src/dialogs/repodialogsettings.cpp \
    ./src/dialogs/repodialoguser.cpp \
    ./src/dialogs/repodialogusermanager.cpp \
    ./src/dialogs/repofederationdialog.cpp \
    ./src/widgets/repofilterabletreewidget.cpp \
    ./src/primitives/repoidbcache.cpp \
    ./src/renderers/repooculustexturerenderer.cpp \
    ./src/dialogs/repoprojectmanagerdialog.cpp \
    ./src/dialogs/repoprojectsettingsdialog.cpp \
    ./src/widgets/reposelectiontreedockwidget.cpp \
    ./src/reposettings.cpp \
    ./src/widgets/repowidgetassimpflags.cpp
FORMS += ./forms/repo_dialogcommit.ui \
    ./forms/repo_dialogconnect.ui \
    ./forms/repo_dialoghistory.ui \
    ./forms/repo_genericdialog.ui \
    ./forms/repo_transformationdialog.ui \
    ./forms/repo_webview.ui \
    ./forms/repo_widgetrepository.ui \
    ./forms/repoabstractmanagerdialog.ui \
    ./forms/repodialogabout.ui \
    ./forms/repodialogoculus.ui \
    ./forms/repodialogsettings.ui \
    ./forms/repodialoguser.ui \
    ./forms/repofederationdialog.ui \
    ./forms/repofilterabletreewidget.ui \
    ./forms/repogui.ui \
    ./forms/repoprojectsettingsdialog.ui \
    ./forms/reposelectiontreedockwidget.ui \
    ./forms/repowidgetassimpflags.ui
RESOURCES += resources.qrc \
    ./submodules/fonts.qrc
